# This pipeline does not implement the analysis template from the 
# project-registry-devops repository because there was an issue with
# analysis of an Angular build when checking out multiple repos.

# This pipeline will trigger on commits or pull-requests made to the branch-dev 
# or main branches.  Note that complete static analysis with SonarCloud is only 
# performed on "long-lived" branches, designated as 'main' and any branch name 
# prefixed with 'branch-'.  A minimal analysis is still performed on "short-lived" 
# branches, and a special analysis is performed on pull requests.
trigger:
- branch-dev
- main
pr:
- branch-dev
- main

# These variable groups are required for sonarCloud and Discord secrets to be
# available for analysis tasks
# The contents of these groups that are used here are:
#  project-registry-sonarcloud: stores sonarcloud variables/secrets
#   - sonarKeyPrefix: the common prefix string for the sonar keys in the project
#       (requires a sonarCloud project key)
#   - sonarNamePrefix: the common prefix string for the project names
#   - sonarOrg: the sonar organization
#   - sonarUrlPrefix: the common prefix string for the url for the results
#  project-registry-discord: stores discord variables/secrets
#   - discordAnalysisChannel: the output channel for discord analysis info
#   - discordAnalysisKey: the webhook key associated with the above channel
variables:
- group: project-registry-sonarcloud
- group: project-registry-discord
- name: microservice
  value: "frontend"
- name: coveragePath
  value: "./p3-frontend/**"
- name: workDir
  value: "./p3-frontend/"

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
  - job: analysis
    steps:
    - checkout: self

    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud'
        organization: $(sonarOrg)
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: $(sonarKeyPrefix)${{ variables.microservice }}
        cliSources: '${{ variables.workDir }}/src,${{ variables.workDir }}/e2e'
        extraProperties: |
          sonar.coverage.exclusions=**/*.spec.ts,${{ variables.workDir }}/e2e/**/*
          sonar.javascript.lcov.reportPaths=${{ variables.workDir }}/coverage/${{ variables.workDir }}/lcov.info
      displayName: Prepare Analysis for ${{ variables.microservice }} --> Task

    - script: npm ci
      workingDirectory: ${{ variables.workDir }}
      displayName: Install dependencies for ${{ variables.microservice }} --> Task

    - script: npm build --prod
      workingDirectory: ${{ variables.workDir }}
      displayName: Build ${{ variables.microservice }} --> Task
    
    - script: npx ng test --browsers ChromeHeadless --no-watch --code-coverage
      workingDirectory: ${{ variables.workDir }}
      displayName: Test ${{ variables.microservice }} --> Task

    - task: SonarCloudAnalyze@1
      condition: always()
      displayName: Analyze ${{ variables.microservice }} --> Task

    - task: SonarCloudPublish@1
      condition: always()
      inputs:
        pollingTimeoutSec: '300'
      displayName: Publish Analysis of ${{ variables.microservice }} --> Task

    - task: 'ado-discord-webhook@1' # <-- See external requirements note above
      condition: always()
      inputs:
        channelId: $(discordAnalysisChannel)
        webhookKey: $(discordAnalysisKey)
        name: $(System.TeamProject)
        messageType: 'content'
        content: | 
          **__Analysis Report__**
          **Status:** $(Agent.JobStatus)
          **Branch:** $(Build.SourceBranch)
          **Trigger:** $(Build.Reason)
          **Message:** $(Build.SourceVersionMessage)
          **Report:** <$(sonarUrlPrefix)$(Build.SourceBranch)&id=$(sonarKeyPrefix)${{ variables.microservice }}>
          **Logs:** <$(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=logs>
          **Repo:** <https://github.com/$(Build.Repository.Name)>

    displayName: Analyze frontend --> Job

    # Dockerize job goes here

  displayName: Build frontend --> Stage 