trigger:
- branch-dev
- main
pr:
- branch-dev
- main

variables:
- group: project-registry-sonarcloud
- group: project-registry-discord
- name: microservice
  value: "frontend"
- name: coveragePath
  value: "./p3-frontend/**"
- name: workDir
  value: "./p3-frontend/"

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
  - job: analysis
    steps:
      - checkout: self

      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: 'SonarCloud'
          organization: $(sonarOrg)
          scannerMode: 'CLI'
          configMode: 'manual'
          cliProjectKey: $(sonarKeyPrefix)${{ variables.microservice }}
          cliSources: './${{ variables.workDir }}'
        displayName: Prepare Analysis for ${{ variables.microservice }} --> Task
            
      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: './${{ variables.workDir }}'
        displayName: Install dependencies for ${{ variables.microservice }} --> Task

      - task: AngularCLI@1
        inputs:
          command: 'build'
          project: './${{ variables.workDir }}'
          prod: false
          DisableAnalytics: true
        displayName: Build ${{ variables.microservice }} --> Task

      - task: SonarCloudAnalyze@1
        displayName: Analyze ${{ variables.microservice }} --> Task

      - task: SonarCloudPublish@1
        condition: always()
        inputs:
          pollingTimeoutSec: '300'
        displayName: Publish Analysis of ${{ variables.microservice }} --> Task

      - task: 'ado-discord-webhook@1'
        condition: always()
        inputs:
          channelId: $(discordAnalysisChannel)
          webhookKey: $(discordAnalysisKey)
          name: ${{ variables.notifactionDisplayName }}
          messageType: 'content'
          content: | 
                **__Analysis Report__**
                **Build Number:** $(Build.BuildNumber)
                **Report:** $(sonarUrlPrefix)$(Build.SourceBranch)&id=$(sonarKeyPrefix)${{ variables.microservice }}
                **Repo:** $(Build.Repository.Name)
                **Branch:** $(Build.SourceBranch)
                **Trigger:** $(Build.Reason)
                **Status:** $(Agent.JobStatus)
        displayName: Notification --> Task
      
    displayName: Analyze frontend --> Job
  displayName: Build frontend --> Stage