trigger:
- Dev

pool:
  vmImage: ubuntu-latest

steps:

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: './p3-frontend/'

- task: AngularCLI@1
  inputs:
    command: 'test'
    project: './p3-frontend/'
    DisableAnalytics: false