resources:
  repositories:
  - repository: templates
    type: github
    endpoint: Team1-Project3
    name: 1053-August-Duet-Project-Registry/project-registry-devops
    ref: refs/heads/feature-templates

trigger:
- branch-dev
- main
pr:
- branch-dev
- main

variables:
- group: project-registry-sonarcloud
- group: project-registry-discord

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
  - job: analysis
    steps:
      - checkout: self
      - checkout: templates
      # - script: |
      #     pwd
      #     ls
      #     cd project-registry-devops/templates
      #     ls
      #     cat analysis.yml
      - template: ./templates/analysis.yml@templates
        parameters:
          microservice: frontend
          coveragePath: "./p3-frontend/**"
          workDir: "./p3-frontend/"
          maven: false
          angular: true
 