# This pipeline relies on the analysis.ng.yml and dockerize.ng.yml templates 
# located in the repository resource descibed below.  Note that these are
# distinct from analysis.yml and dockerize.yml, which are for maven builds.
# The ref: value must point to a branch where both templates exist.
resources:
  repositories:
  - repository: templates
    type: github
    endpoint: Team1-Project3
    name: 1053-August-Duet-Project-Registry/project-registry-devops
    ref: refs/heads/feature-dockerpipe

# This pipeline will trigger on commits or pull-requests made to the branch-dev 
# or main branches.  Note that complete static analysis with SonarCloud is only 
# performed on "long-lived" branches, designated as 'main' and any branch name 
# prefixed with 'branch-'.  A minimal analysis is still performed on "short-lived" 
# branches, and a special analysis is performed on pull requests.
trigger:
- branch-dev
- main
pr:
- branch-dev
- main

# These variable groups are required for sonarCloud and Discord secrets to be
# available for analysis tasks
# The contents of these groups that are used here are:
#  project-registry-sonarcloud: stores sonarcloud variables/secrets
#   - sonarKeyPrefix: the common prefix string for the sonar keys in the project
#       (requires a sonarCloud project key)
#   - sonarNamePrefix: the common prefix string for the project names
#   - sonarOrg: the sonar organization
#   - sonarUrlPrefix: the common prefix string for the url for the results
#  project-registry-discord: stores discord variables/secrets
#   - discordAnalysisChannel: the output channel for discord analysis info
#   - discordAnalysisKey: the webhook key associated with the above channel
variables:
# secrets
- group: project-registry-sonarcloud
- group: project-registry-discord

# global
- name: microservice
  value: "frontend"

# analysis
- name: coveragePath
  value: "./p3-frontend/**"
- name: workDir
  value: "./p3-frontend/"

# docker
- name: imageName
  value: project-registry-frontend
- name: containerRepo
  value: jpbulloch5
- name: containerServiceConnection
  value: 'Jacob''s Docker Hub'
- name: containerUrl
  value: https://hub.docker.com/repository/docker/jpbulloch5/project-registry-frontend
- name: version
  value: undefined

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
  - job: analysis
    steps:
    - template: ./templates/analysis.ng.yml@templates
      parameters:
        coveragePath: "./p3-frontend/**"
        workDir: "./p3-frontend/"
        sonarKeyPrefix: $(sonarKeyPrefix)
        sonarNamePrefix: $(sonarNamePrefix)
        sonarOrg: $(sonarOrg)
        sonarUrlPrefix: $(sonarUrlPrefix)
        discordChannel: $(discordAnalysisChannel)
        discordKey: $(discordAnalysisKey)

    displayName: Analyze frontend --> Job

  displayName: Analyze frontend --> Stage 

- stage: dockerize
  dependsOn: []
  jobs:
  - job: dockerize

    steps:

    # script explanation: https://gist.github.com/DarrenN/8c6a5b969481725a4413
    - script: |
        # Version key/value should be on its own line
        VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
        echo found angular package version: $VERSION
        echo "##vso[task.setvariable variable=version]$VERSION"
      workingDirectory: ${{ variables.workDir }}
      displayName: Extract Angular Package Version --> Task

    - task: Docker@2
      inputs:
        containerRegistry: ${{ variables.containerServiceConnection }}
        repository: '${{ variables.containerRepo }}/${{ variables.imageName }}'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: $(version)
      displayName: Dockerize ${{ variables.imageName }} and push --> Task
    
    - task: ado-discord-webhook@1
      condition: always()
      inputs:
        channelId: $(discordDockerChannel)
        webhookKey: $(discordDockerKey)
        name: '$(System.TeamProject) - Docker'
        avatar: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn3.iconfinder.com%2Fdata%2Ficons%2Flogos-and-brands-adobe%2F512%2F97_Docker-512.png&f=1&nofb=1'
        messageType: 'content'
        content: |
          **__Dockerization Report__**
          **Status:** $(Agent.JobStatus)
          **Branch:** $(Build.SourceBranch)
          **Trigger:** $(Build.Reason)
          **Message:** $(Build.SourceVersionMessage)
          **Image:** ${{ variables.imageName }}:${{ variables.version }}
          **Container Repo:** <${{ variables.containerUrl }}>
          **Logs:** <$(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=logs>
          **Repo:** <$(Build.Repository.Uri)/tree/$(Build.SourceBranchName)>
      displayName: Notification --> Task

    displayName: Dockerize frontend --> Job
  displayName: Dockerize frontend --> Stage 