resources:
  repositories:
  - repository: templates
    type: github
    endpoint: Team1-Project3
    name: 1053-August-Duet-Project-Registry/project-registry-devops
    ref: refs/heads/feature-templates

trigger:
- branch-dev
- main
pr:
- branch-dev
- main

variables:
- group: project-registry-sonarcloud
- group: project-registry-discord

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
  - job: analysis
    steps:
      - checkout: self
      - checkout: templates
      - template: ./templates/analysis.yml@templates
        parameters:
          microservice: frontend
          coveragePath: "./p3-frontend/**"
          workDir: "$(Build.Repository.LocalPath)/project-registry-frontend/p3-frontend/"
          maven: false
          angular: true
          sonarOrg: ${{ sonarOrgName }}
          sonarName: ${{ sonarFrontendName }}
          sonarKey: ${{ sonarFrontendKey }}
          projectName: Team1-Project3
          projectOrg: revature-training-uta 
          sonarUrlPrefix: https://sonarcloud.io/dashboard?branch=$(Build.SourceBranch)&id=
          gitUrlPrefix: https://github.com/1053-August-Duet-Project-Registry/project-registry-
          discordId: ${{ discord-channel-id }}
          discordKey: ${{ discord-channel-id }}