resources:
  repositories:
  - repository: devopsTemplates
    type: github
    endpoint: Team1-Project3
    name: 1053-August-Duet-Project-Registry/project-registry-devops
    ref: feature-templates

trigger:
- branch-dev
- main
pr:
- branch-dev
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
  - template: templates/analysis.yml
    parameters:
      microservice: frontend
      coveragePath: "./p3-frontend/**"
      workDir: "./p3-frontend/"
      maven: false
      angular: true
 